apiVersion: v1
data:
  {{- toYaml .Values.secret | nindent 2 }}
kind: Secret
metadata:
  name: {{ include "aliyundriver.fullname" . }}-secret
  labels:
    {{- include "aliyundriver.labels" . | nindent 4 }}
type: Opaque
